notebooks_manager/notebooks_manager/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'notebooks_manager.views.home', name='home'),
    # url(r'^notebooks_manager/', include('notebooks_manager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'notebooks_manager.views.viewCoursesAndShipmentsWeeks', name='home'),
    url(r'^notebook/new/$', 'notebooks_manager.views.addNotebook'),
    url(r'^notebook/view/$', 'notebooks_manager.views.viewNotebooks', name='notebook_view'),
    url(r'^notebook/edit/(?P<notebook_id>\d+)/$', 'notebooks_manager.views.addNotebook', name="notebook_edit"),
    url(r'^notebook/delete/(?P<notebook_od>\d+)/$', 'notebooks_manager.views.deleteNotebook'),
#     url(r'^notebook/success/(?P<notebookID>\d+)/$', 'notebooks_manager.views.addNotebookOnSuccess', name="notebook_new_success"),
    url(r'^shipment/new/$', 'notebooks_manager.views.addShipment', name="shipment_new"),
    url(r'^shipment/view/$', 'notebooks_manager.views.viewShipments', name='view_shipment'),
    url(r'^shipment/edit/(?P<shipment_id>\d+)/$', 'notebooks_manager.views.editShipment', name="edit_shipment"),
    url(r'^shipment/delete/(?P<shipment_id>\d+)/$', 'notebooks_manager.views.deleteShipment', name="delete_shipment"),
#     url(r'^shipment/success/(?P<shipmentID>\d+)/$', 'notebooks_manager.views.addShipmentOnSuccess', name="shipment_new_success"),
    url(r'^course/new/$', 'notebooks_manager.views.addCourse', name="course_new"),
    url(r'^course/edit/(?P<course_id>\d+)/$', 'notebooks_manager.views.addShipmentToCourse', name="course_edit"),
    url(r'^course/view/$', 'notebooks_manager.views.viewCourses', name="view_courses"),
    url(r'^course/confirm/(?P<course_id>\d+)/$', 'notebooks_manager.views.confirmCourse', name='confirm_course'),    
#     url(r'^course/addShipment/$', 'notebooks_manager.views.addShipment'),
    url(r'^course/addShipment/(?P<course_id>\d+)/$', 'notebooks_manager.views.addShipmentToCourse'),
    url(r'^course/delete/(?P<course_id>\d+)/$', 'notebooks_manager.views.deleteCourse'),
    url(r'^course/weekView/$', 'notebooks_manager.views.viewCoursesAndShipmentsWeeks')
#     url(r'^course/edit/(?P<courseID>\d+)#(?P<shipmentID>\d+)/$', 'notebooks_manager.views.editCourse', name="course_edit"),
#     url(r'^course/success/(?P<courseID>\d+)/$', 'notebooks.views.addCourseOnSuccess', name="course_new_success"),
#     url(r'^course/failure/$', 'notebooks.views.addCourseOnFailure', name="course_new_failure"),
)

notebooks_manager/notebooks_manager/models.py
'''
Created on 18-06-2013

@author: bambo
'''
from django.db import models
from django.db.models.signals import pre_delete, post_save
from django.dispatch.dispatcher import receiver
class Place(models.Model):
    name = models.CharField(max_length=64, verbose_name='place')
    def __unicode__(self):
        return self.name
    def __str__(self):
        return self.name   
    
    
class Notebook(models.Model):
    LIVE = 1
    BROKEN = 2
    TRASHED = 3
    WORKING_STATUS = (
                      (LIVE, 'live'),
                      (BROKEN, 'broken'),
                      (TRASHED, 'trashed'),
                      )
    
    FREE = 1
    COURSE = 2
    TRENER = 3
    LENT = 4
    RESERVED = 5
    SHIPMENT = 6
    STATUS_CHOICE = (
                     (FREE, 'free'),
                     (COURSE,'in course'),
                     (TRENER, 'trener'),
                     (LENT, 'lent'),
                     (RESERVED, 'reserved'),
                     (SHIPMENT, 'shipment')
                     )
    brand = models.CharField(max_length=64, verbose_name='brand')
    model = models.CharField(max_length=64, verbose_name="Model")
    localization = models.ForeignKey(Place, verbose_name='Place')
    serial = models.CharField(max_length=64, verbose_name="Serial no.")
    working = models.IntegerField(choices = WORKING_STATUS, default = LIVE)
    status = models.IntegerField(choices = STATUS_CHOICE, default = FREE)
    notes = models.CharField(max_length=512, verbose_name="Notes", null=True)
    
    
    
    def __unicode__(self):
        return "<Notebook m:%s s:%s l:%s w:%s s:%s n:%s>" % (self.model, self.serial, self.localization,
                                                             self.working, self.status, self.notes)

class Shipment(models.Model):
    READY = 1
    IN_PROGRESS = 2
    FINISHED = 3
    DELAYED = 4
    NOT_PREPARED = 5
    STATUS = (
              (NOT_PREPARED, 'not prepared'),
              (READY, 'ready'),
              (IN_PROGRESS, 'in progress'),
              (FINISHED, 'finished'),
              (DELAYED, 'delayed/broken/something went terribly wrong'),
         )
    shipment_date = models.DateField(verbose_name = "designed shipment date")
    delivery_date = models.DateField(verbose_name = 'designed delivery date')
    shipment_from = models.ForeignKey(Place, verbose_name="shipment from", related_name="place_from")
    shipment_to = models.ForeignKey(Place, verbose_name="shipment to", related_name="place_to")
    shipment_status = models.IntegerField(choices = STATUS, default = NOT_PREPARED)
    notes = models.CharField(max_length=2048, verbose_name="notes", blank=True,null=True)
    notebooks = models.ManyToManyField(Notebook, verbose_name="notebooks", blank=True, null=True)
    
    def __unicode__(self):
        return "<Shipment id:%s | %s -> %s " %(self.id, self.shipment_from, self.shipment_to)
    
    class Meta:
        ordering = ['-shipment_date',]

    
class Course(models.Model):
    NOT_CONFIRMED = 1
    CONFIRMED = 2
    STATUS = (
              (NOT_CONFIRMED, 'not confirmed'),
              (CONFIRMED, 'confirmed'),
              )
    
    name = models.CharField(max_length=64, verbose_name='course name')
    start_date = models.DateField('start date')
    end_date = models.DateField('end field')
    localization = models.ForeignKey(Place, verbose_name="place")
    shipments = models.ManyToManyField(Shipment, verbose_name="shipments", null=True, default=None)
    notebooks = models.ManyToManyField(Notebook, verbose_name='notebooks', null=True, default=None)
    participants = models.IntegerField()
    notes = models.CharField(max_length=512, verbose_name="notes", null=True)
    course_status = models.IntegerField(choices = STATUS, default=NOT_CONFIRMED) 
    def __unicode__(self):
        return "<Course n:%s, sd:%s, ed:%s, p:%s, n%s>" %(self.name,
                                                                      self.start_date, self.end_date, self.participants, self.notes)
  
  
@receiver(pre_delete, sender=Course)
def courseDeleteHandler(sender, **kwargs):
    """
    Sets notebooks states assigned to the course again on free after the course had been deleted.
    """
    course_instance = kwargs['instance']
    for notebook in course_instance.notebooks.all():
        notebook.status = Notebook.FREE
        notebook.save()
    for shipment in course_instance.shipments.all():
        shipment.delete()
        
@receiver(post_save, sender=Shipment)
def updateNotebookPlase(sender, **kwargs):
    """
    Update Notebook place of being
    """
    shipment_instance = kwargs['instance']
    
    for notebook in shipment_instance.notebooks.all():
        if shipment_instance.shipment_status == Shipment.FINISHED:
            notebook.localization = shipment_instance.shipment_to
        if shipment_instance.shipment_status == Shipment.NOT_PREPARED:
            notebook.localization = shipment_instance.shipment_from;
        notebook.save()
    
    

notebooks_manager/notebooks_manager/views.py
#coding: utf-8
from collections import defaultdict
from datetime import date, timedelta
import datetime
import json

from django.core import serializers
from django.forms.formsets import formset_factory
from django.http import response
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404, \
    redirect
from django.template.context import RequestContext
from django.utils import simplejson
from django_tables2.config import RequestConfig

from notebooks_manager.forms import addNotebookForm, addCourseForm, \
    addShipmentForm, DateForm
from notebooks_manager.models import Notebook, Shipment, Course, Place
from notebooks_manager.tables import NotebookTable, ShipmentTable, CourseTable, \
    NotebookEditTable, FinishedCourseTable, NotebookTableWOStatus, NotebookDashTable
from notebooks_manager.utils import next_weekday, get_or_none, \
    getNotebooksListOnDate, getNotebooksListBetweenDates, weekday, \
    getCoursesListBetweenDates, dashboard


def homePage(request):
    
    return render(request   , 'home.html')


def addNotebook(request, notebook_id = None):
    if ( notebook_id ):
        notebook_instance = Notebook.objects.get(pk = notebook_id or None)
    else:
        notebook_instance = None
    if request.method == 'POST':
        
        form = addNotebookForm(request.POST, instance=notebook_instance)
        if form.is_valid():
            notebook_instance = form.save()
            if(notebook_id):
                confirmMessage = "Pomyślnie zmodyfikowano "
            else:
                confirmMessage = "Pomyślnie dodano"
            confirmMessage += " notebooka %s." % notebook_instance.serial
            print confirmMessage
            return render(request, 'addNotebook.html',{
                                                       'addNotebookForm' : form,
                                                       'confirmMessage': confirmMessage})
            
    else:
        form = addNotebookForm(request.POST or None, instance = notebook_instance)
        return render(request, 'addNotebook.html',{
                                                'addNotebookForm': form,
                                                } )
    
    
def viewNotebooks(request):
#     d = datetime.date(2013,9,10)
    if request.method == 'POST':
#         print request.POST
        day = int(request.POST['date_day'])
        month = int(request.POST['date_month'])
        year = int(request.POST['date_year'])
        day1 = int(request.POST['date1_day'])
        month1 = int(request.POST['date1_month'])
        year1 = int(request.POST['date1_year'])
        date = datetime.date(year, month, day)
        date1 = datetime.date(year1,month1,day1)
    else:
        date = next_weekday(datetime.date.today(), 0)
        date1 = next_weekday(datetime.date.today(), 0) + timedelta(days=4)
    dateForm = DateForm(initial = {'date': date, 'date1': date1})
    notebooks_instances = getNotebooksListBetweenDates(date,date1)
    for n in notebooks_instances:
        notebooks = NotebookEditTable(notebooks_instances)
    notebookDashTable = NotebookDashTable(notebooks_instances).getHtml()
    
    
    if request.method == 'POST':
        return HttpResponse(simplejson.dumps({'notebooks':notebooks.as_html(),
                                               'dashTable': notebookDashTable}), mimetype="application/json")
    else:
        return render_to_response('viewNotebooks.html', {'notebooks' : notebooks, 'dateForm': dateForm, 
                                                         'dashTable': notebookDashTable},
                              context_instance = RequestContext(request))


def deleteNotebook(request, notebook_id=None):
    uri = request.META.get('HTTP_REFERER') or '/course/view'
    notebook = get_or_none(Notebook, pk=notebook_id)
    if notebook != None:
        notebook.delete()
    return redirect(uri)


def addCourse(request, course_id=None):
    """
    View is responsible for adding new Courses and its' shipments, or editing existing ones
    """

    
    if request.method == 'POST':
        if request.POST['key'] == 'addCourse':
            placePk = request.POST["localization"]
            place = get_or_none(Place, pk=placePk)
            
            if(place == None):
                #check for duplicate name
                place = get_or_none(Place, name=placePk)
#                 print place
                if(place == None):#no duplicated name - creating new place
                    place = Place(name = placePk)
                    place.save()
                POST = request.POST.copy()
                POST["localization"] = place.id
#                 print POST
                cf = addCourseForm(POST)
            else:
                cf = addCourseForm(request.POST)
            
            cf_valid = cf.is_valid()
#             print request.POST
            if cf_valid: 
                c = cf.save()
                nbks = request.POST.getlist("selection")
                nbks_objects = Notebook.objects.filter(pk__in=nbks)
#                 print nbks_objects
            
                shipment_places = defaultdict(list)
                
                for notebook in nbks_objects:
                    if notebook.status == Notebook.FREE:
                        c.notebooks.add(notebook)
                        notebook.save()
                        if notebook.localization != c.localization:
#                             print "Dodaje"
                            shipment_places[notebook.localization].append(notebook)
                    else:
                        pass#jakies jqeury sprawdzajace juz przy zaznaczaniu,albo na poziomie renderowania tabeli
                if shipment_places.__len__() != 0:
                    for k,v in shipment_places.iteritems():
                        sh = Shipment()
                        sh.shipment_date = c.start_date - timedelta(days=3)
                        sh.delivery_date = c.start_date - timedelta(days=1)
                        sh.shipment_to = c.localization
                        sh.shipment_from = k
                        sh.save()
                        c.shipments.add(sh)
                        c.save()
                        for notebook in v:
                            sh.notebooks.add(notebook)
                    destination = '/course/addShipment/%s/' % c.id
                else:
                    destination = "/course/view"
                return HttpResponse(simplejson.dumps({'destination': destination}))
            else:
                pass #form validation error handling
        elif request.POST['key'] == 'refresh':
            year1 = int(request.POST['start_date_year'])
            month1 = int(request.POST['start_date_month'])
            day1 = int(request.POST['start_date_day'])
            year2 = int(request.POST['end_date_year'])
            month2 = int(request.POST['end_date_month'])
            day2 = int(request.POST['end_date_day'])
            date1 = datetime.date(year1, month1, day1)
            date2 = datetime.date(year2, month2, day2)
            notebooks = NotebookTable(getNotebooksListBetweenDates(date1, date2))
            return HttpResponse(simplejson.dumps({'notebooks':notebooks.as_html()}), mimetype="application/json")
        
    else:
        next_monday = next_weekday(date.today(), 0)
        next_friday = next_monday + timedelta(days=4)
        c = Course()
        c.start_date = next_monday
        c.end_date = next_friday
        
        cf = addCourseForm(instance = c)
        notebookTable = NotebookTable(getNotebooksListBetweenDates(c.start_date, c.end_date))
        RequestConfig(request, paginate=False).configure(notebookTable)
        return render(request,'addCourse.html', {'notebooks': Notebook.objects.all(),
                                             'addCourseForm': cf,
                                             'notebookTable': notebookTable,
                                             'dashboard': dashboard(),
                                             })
        
        
def addCourseOnSuccess(request):
    pass


def addCourseOnFailure(request):
    pass


def viewCourses(request):
#     courseTable = CourseTable(Course.objects.all()) 
    courses = Course.objects.all()
    today = datetime.date.today()
    finished = [c for c in courses if c.end_date <= today]
    ongoing = [c for c in courses if c.start_date <= today and c.end_date > today]
    incoming = [c for c in courses if c.start_date > today]
    finishedTable = FinishedCourseTable(finished)
    ongoingTable = CourseTable(ongoing)
    incomingTable = CourseTable(incoming)
    return render(request,'viewCourses.html', {'ongoingTable': ongoingTable, 'finishedTable': finishedTable,
                                               'incomingTable': incomingTable})


def deleteCourse(request, course_id=None):
    uri = request.META.get('HTTP_REFERER') or '/course/view'
    course = get_or_none(Course, pk=course_id)
    if course != None:
        course.delete()
    return redirect(uri)

def confirmCourse(request, course_id=None):
    uri = request.META.get('HTTP_REFERER') or '/course/view'
    course = get_or_none(Course, pk=course_id)
    if course != None:
        course.course_status = Course.CONFIRMED
        course.save()
    for shipment in course.shipments.all():
        return_shipment = Shipment(shipment_date=course.end_date, delivery_date=course.end_date,
                                     shipment_from = course.localization, shipment_to = shipment.shipment_from) 
        return_shipment.save()
        return_shipment.notebooks = shipment.notebooks.all()
        course.shipments.add(return_shipment)
    course.save()
    return redirect(uri)   
    
def addShipment(request, shipment_id=None):
    
    if request.method == "POST":

notebooks_manager/notebooks_manager/templates/addCourse.html
{% extends "home.html" %}

{% block scripts %}

<script type="text/javascript">
function addSerialFilter()
{
	$('#notebook_table_filter').append('<br><label>Serial: <input type="text" id="serial"></label>');
    
    $("input#serial").keyup(function() 
    {
        var self = $(this);
        console.log(self.val().split(','));
        var array = self.val().split(',');
        $("tbody tr").hide();
        
        for (var i in array)
        {
            console.log(array[i]);
            var keyword = array[i].replace(/\s/g, "");
            $("tbody tr td.serial").each(function()
            {
            	console.log($(this).parent());
                if($(this).text().toLowerCase().indexOf(keyword) >= 0){
                    $(this).parent().show();
                }
            });
        } 
    });
}
$(document).ready(function() {
$.ajaxSetup({beforeSend: function(xhr, settings){
     xhr.setRequestHeader('X-CSRFToken', 
                          '{{ csrf_token }}');
   }});
    $('#notebook_table').dataTable( {
      "sDom": 'frt' ,
      "iDisplayLength": 250,
      "aoColumns": [
			null,
			null,
			null,
			null,
			null,null,null,null,{ "bSortable": false }
			],
    });
        console.log($('notebook_table_filter'))
        addSerialFilter()
    
    
    $("#submit_button").click(function() 
	{
		
		var url="{{ SITE_URL }}";
		var data_ = "key=addCourse&" + $("#addCourse").serialize() + "&" +  $("#addNotebooks2Course").serialize(); 
		console.log(data_);
		$.ajax(
		{
			type: "POST",
			url: url,
			data: data_,
			success: function(response){
				response = JSON.parse(response)
				window.location.href = response.destination;
			}
		});
	});
	$("#refresh_button").click(function()
	{	
		var data = "key=refresh&" + $("#id_end_date_day").serialize() +  '&' +$("#id_end_date_month").serialize() +'&' + $("#id_end_date_year").serialize() + '&' +$("#id_start_date_day").serialize() +'&' + $("#id_start_date_month").serialize() + '&' +$("#id_start_date_year").serialize()
		console.log(data)
		$.ajax(
		{
			type: "POST",
			url: "{{SITE_URL}}",
			data: data,
			success: function(data, status, xhr)
    		{
    			console.log(data)
    			$("#notebook_table_wrapper").replaceWith(data['notebooks'])
    			$("#notebook_table_wrapper").attr("id","notebook_table")
    			 $('#notebook_table').dataTable( 
    			 {
      "sDom": 'frt' ,
      "iDisplayLength": 250,
      "aoColumns": [
			null,
			null,
			null,
			null,
			null,null,null,null,{ "bSortable": false }
			],
    });
    addSerialFilter()
        	}
		});
	});
	
	$("#id_localization").parent().append('<span id="new_localization">+</span><input id="id_localization_hidden" disabled="true" maxlength="64" name="localization" type="text"><span id="new_localization_disable">-</span>');
	$("#id_localization_hidden").hide()
	$("#new_localization_disable").hide()
	
	$("#new_localization").click(function()
	{
		$("#id_localization_hidden").show()
		$("#id_localization_hidden").removeAttr("disabled")
		$("#id_localization").hide()
		$("#id_localization").attr("disabled","true")
		$("#id_localization").attr("id","tmp")
		$("#id_localization_hidden").attr("id","id_localization")
		$("#tmp").attr("id", "id_localization_hidden")
		$(this).hide()
		$("#new_localization_disable").show()
	});
	$("#new_localization_disable").click(function()
	{
		$("#id_localization_hidden").show()
		$("#id_localization").hide()
		$("#id_localization").attr("disabled","true")
		$("#id_localization").attr("id","tmp")
		$("#id_localization_hidden").attr("id","id_localization")
		$("#tmp").attr("id", "id_localization_hidden")
		$("#id_localization").removeAttr("disabled")
		$(this).hide()
		$("#new_localization").show()
	});
	$("#selectall").click(function()
	{
		$("input[name='selection']:visible").each(function(){
			$(this).prop("checked", !$(this).prop("checked"));
		});
	});
} );
</script>

{% endblock %}

{% block content %}
{% load render_table from django_tables2 %}
<form action="/addCourse/" method="POST" id="addCourse">
	{% csrf_token %}
	{{ addCourseForm.as_p }}
</form>
<p id="p_submit">
	<input type="submit" value="Submit" id="submit_button">
	<input type="submit" value="Odśwież" id="refresh_button">
</p>
<hr>
<form action="/addNotebooksToCourse" method="POST" id="addNotebooks2Course">
{% if notebooks != None %}
	{% render_table notebookTable %}
	{% endif %}
</form>

{% endblock %}

notebooks_manager/notebooks_manager/templates/addNotebook.html
{% extends "home.html" %}
{% block content %}
{% if confirmMessage != None %}
	<p id="id_message_bar">{{confirmMessage}}</p>
{% endif %}
<form action="{{SITE_URL}}" method="POST">
	{% csrf_token %}
	{{ addNotebookForm.as_p }}
	<input type="submit" value="Submit" id="id_submit_new_notebook_button">
</form>
{% endblock %}

notebooks_manager/notebooks_manager/templates/addShipment.html
{% extends "home.html" %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {
 $.ajaxSetup({beforeSend: function(xhr, settings){
     xhr.setRequestHeader('X-CSRFToken', 
                          '{{ csrf_token }}');
   }});
   
    $('#notebook_table').dataTable( {
      "sDom": 'frt' ,
      "iDisplayLength": 250,
      "aoColumns": [
			null,
			null,
			null,
			null,
			null,null,null,null,{ "bSortable": false }
			],
    });

    $("#submit_button").click(function() 
	{
		
		var url="{{ SITE_URL }}";
		var data_ = $("#addShipment").serialize() + "&" +  $("#addNotebooks").serialize(); 
		console.log(data_);
		$.ajax(
		{
			type: "POST",
			url: url,
			data: data_,
			success: function(response){
				response = JSON.parse(response)
				window.location.href = response.destination;
			}
		});
	});
});
</script>
{% endblock %}
{% block content %}
{% load render_table from django_tables2 %}
<input type="submit" value="Zapisz" id="submit_button">
<form action="{{ SITE_URL }}" method="POST" id="addShipment">
	{% csrf_token %}
	{{ shipmentForm.as_p }}
</form>
<form action="{{SITE_URL}}" method="POST" id="addNotebooks">
	{% render_table notebookTable %}
</form>
{% endblock %}

notebooks_manager/notebooks_manager/templates/addShipmentToCourse.html
{% extends "home.html" %}
{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
 $.ajaxSetup({beforeSend: function(xhr, settings){
     xhr.setRequestHeader('X-CSRFToken', 
                          '{{ csrf_token }}');
   }});

    $("#all_submit_button").click(function() 
	{	var form = $("#course_edit_form")
			$.ajax({
			type: "POST",
			url: "{{SITE_URL}}",
			data: "key=course&" + JSON.stringify(form.serialize())
		});
		
		$('.shipment_edit_form').each(function()
		{
			$.ajax({
			type: "POST",
			url: "{{SITE_URL}}",
			data: "key=shipment&" + JSON.stringify($(this).serialize()),
			});
		});
		
		$.ajax({
			type: "POST",
			url: "{{SITE_URL}}",
			data: "key=redirect&",
			success: function(response){
				response = JSON.parse(response)
				window.location.href = response.destination;
			}
		});
	});
	
});
</script>
{% endblock %}

{% block content %}
{% load render_table from django_tables2 %}
<input type="submit" value="Zapisz" id="all_submit_button">
<form action="" method="POST" id="course_edit_form">
	{% csrf_token %}
	{{ courseForm.as_p }}
</form>

{% if localNotebooks %}
<hr>Local notebooks:
{% render_table localNotebooks %}
{% endif %}
<hr>
<p id="formset">
{% for k,v in shipmentFormsAndNotebooks.iteritems %}
<form action="" method="POST" class="shipment_edit_form">
	{% csrf_token %}
	{{ k.id }}
	{{ k.as_p }}
	<form class="shipment_notebooks">
	{% csrf_token %}
	{% render_table v %}
	</form>
</form>
<hr>
{% endfor %}
</p>
{% endblock %}

notebooks_manager/notebooks_manager/templates/editCourse.html
{% extends "home.html" %}
{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
 $.ajaxSetup({beforeSend: function(xhr, settings){
     xhr.setRequestHeader('X-CSRFToken', 
                          '{{ csrf_token }}');
   }});

    $("#shipment_submit_button").click(function() 
	{	
		jsonArray = [];
		$('.shipment_edit_form').each(function()
		{
			jsonArray.push($(this).serialize());
			$.ajax({
			type: "POST",
			url: "{{SITE_URL}}",
			data: JSON.stringify($(this).serialize()),
			});
		});
	});
});
</script>
{% endblock %}

{% block content %}
<form action="/course/addShipment/" method="POST" id="course_edit_form">
	<input type="submit" value="Zapisz szkolenie" id="all_submit_button">
	{% csrf_token %}
	{{ courseForm.as_p }}
</form>

<hr>
<input type="submit" value="Zapisz wysyłki" id="shipment_submit_button">
<p id="formset">
{% for k,v in shipmentFormsAndNotebooks.iteritems %}
<form action="/course/addShipment" method="POST" class="shipment_edit_form">
	{% csrf_token %}
	{{ k.id }}
	{{ k.as_p }}
	<form class="shipment_notebooks">
	{% render_table v %}
	</form>
</form>
<hr>
{% endfor %}
</p>
<p id="free_notebooks">
<input type="submit" value="Generuj dodatkowe wysyłki"
{% render_table free_notebooks %}
</p>
{% endblock %}

notebooks_manager/notebooks_manager/templates/viewCourses.html
{% extends "home.html" %}
{% block scripts %} 
<script type="text/javascript">
$(document).ready(function(){
	$("#courses_table").dataTable( {
      "sDom": 'frt' ,
      "iDisplayLength": 250
    });
});
</script>
{% endblock %}

{% block content %}

{% load render_table from django_tables2 %}
	{% if incomingTable != None %}
	<h1>Nadchodzące</h1>
	{% render_table incomingTable %}
	{% endif %}
	
	{% if ongoingTable != None %}
	<h1>Trwające</h1>
	{% render_table ongoingTable %}
	{% endif %}
	{% if finishedTable != None %}
	<h1>Zakończone</h1>
	{% render_table finishedTable %}
	{% endif %}
	
	

{% endblock %}

notebooks_manager/notebooks_manager/templates/viewShipments.html
{% extends "home.html" %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
	$("#shipments_table").dataTable( {
      "sDom": 'frt' ,
      "iDisplayLength": 250
    });
});
</script>
{% endblock %}

{% block content %}
{% load render_table from django_tables2 %}
	{% if shipments != None %}
	{% render_table shipments %}
	{% endif %}
{% endblock %}